---
#      _                          _    __          __     ___            _        
#   __| | _____   _____  ___ ___ | |_ / /__ _ __ __\ \   / / |_ __ _ ___| | _____ 
#  / _` |/ _ \ \ / / _ \/ __/ _ \| __| / __| '__/ __| | / /| __/ _` / __| |/ / __|
# | (_| | (_) \ V /  __/ (_| (_) | |_| \__ \ | | (__| |/ / | || (_| \__ \   <\__ \
#  \__,_|\___/ \_/ \___|\___\___/ \__| |___/_|  \___| /_/   \__\__,_|___/_|\_\___/
#                                     \_\          /_/                            
# boot-script
- name: boot-script | FreeBSD | /etc/init.d/{{ dovecot.initscript }} should be deployed
  when: ansible_os_family == "FreeBSD"
  template:
    src:   "etc/init.d/dovecot.FreeBSD.j2"
    dest:  "/usr/local/etc/rc.d/{{ dovecot.initscript }}"
    mode:  "0755"
    owner: "root"
    group: "wheel"

- block:
    - name: boot-script | RedHat | /etc/init.d/{{ dovecot.initscript }} should be deployed
      when: ansible_distribution_major_version < 7
      template:
        src:   "etc/init.d/dovecot.RedHat.j2"
        dest:  "/etc/init.d/{{ dovecot.initscript }}"
        mode:  "0755"
        owner: "root"
        group: "root"

    - name: boot-script | RedHat | Install /etc/rc.d/init.d/{{ dovecot.initscript }}
      when: ansible_distribution_major_version < 7
      shell: >
        /sbin/chkconfig --add {{ dovecot.initscript }}
      args:
        creates: "/etc/rc.d/rc0.d/K15{{ dovecot.initscript }}"

    - name: boot-script | RedHat | /usr/lib/systemd/system/{{ dovecot.initscript }}.service should be deployed
      when: ansible_distribution_major_version > 6
      register: deploy_dovecot_service_unit
      template:
        src:   "usr/lib/systemd/system/dovecot.service.j2"
        dest:  "/usr/lib/systemd/system/{{ dovecot.initscript }}.service"
        mode:  "0644"
        owner: "root"
        group: "root"

    - name: boot-script | RedHat | /usr/lib/systemd/system/{{ dovecot.initscript }}.socket should be deployed
      when: ansible_distribution_major_version > 6
      register: deploy_dovecot_socket_unit
      template:
        src:   "usr/lib/systemd/system/dovecot.socket.j2"
        dest:  "/usr/lib/systemd/system/{{ dovecot.initscript }}.socket"
        mode:  "0644"
        owner: "root"
        group: "root"

    - name: boot-script | RedHat | {{ dovecot.serverroot }}/libexec/call-before-start should be deployed
      when: ansible_distribution_major_version > 6
      template:
        src:   "opt/dovecot/libexec/call-before-start.j2"
        dest:  "{{ dovecot.serverroot }}/libexec/call-before-start"
        mode:  "0755"
        owner: "root"
        group: "root"

    - name: boot-script | RedHat | {{ dovecot.initscript }} should be reloaded
      when: ansible_distribution_major_version > 6 and
            ( deploy_dovecot_service_unit|changed or deploy_dovecot_socket_unit|changed )
      shell: systemctl daemon-reload
  when: ansible_os_family == "RedHat"

- name: boot-script | Turn on init script
  when: dovecot.enabled == true
  service:
    name:    "{{ dovecot.initscript }}"
    enabled: "yes"

- name: boot-script | Turn off init script
  when: dovecot.enabled == false
  service:
    name:    "{{ dovecot.initscript }}"
    enabled: "no"

- name: Start dovecot
  when: dovecot.started == true
  service:
    name:  "{{ dovecot.initscript }}"
    state: "started"

- name: Stop dovecot
  when: dovecot.started == false
  service:
    name:  "{{ dovecot.initscript }}"
    state: "stopped"

