---
#      _                          _    __          __     ___            _        
#   __| | _____   _____  ___ ___ | |_ / /__ _ __ __\ \   / / |_ __ _ ___| | _____ 
#  / _` |/ _ \ \ / / _ \/ __/ _ \| __| / __| '__/ __| | / /| __/ _` / __| |/ / __|
# | (_| | (_) \ V /  __/ (_| (_) | |_| \__ \ | | (__| |/ / | || (_| \__ \   <\__ \
#  \__,_|\___/ \_/ \___|\___\___/ \__| |___/_|  \___| /_/   \__\__,_|___/_|\_\___/
#                                     \_\          /_/                            
# make-config
- name: make-config | Sub directories in etc/ should be created
  file:
    path:  "{{ dovecot.serverroot }}/{{ item }}"
    mode:  "0755"
    owner: "root"
    state: "directory"
  with_items:
    - "etc/tls"
    - "etc/conf.d"

- name: make-config | Sub directories in var/ should be created
  file:
    path:  "{{ dovecot.serverroot }}/{{ item }}"
    mode:  "0755"
    owner: "{{ dovecot.user.daemon.username }}"
    group: "{{ dovecot.user.daemon.group }}"
    state: "directory"
  with_items:
    - "var/log"
    - "var/run"

- name: make-config | etc/dovecot.conf should be deployed
  notify: Restart dovecot
  template:
    src:   "opt/dovecot/etc/dovecot.conf.j2"
    dest:  "{{ dovecot.serverroot }}/etc/dovecot.conf"
    mode:  "0644"
    owner: "root"

- name: make-config | Config files in etc/ directory should be deployed
  template:
    src:   "opt/dovecot/etc/{{ item }}.j2"
    dest:  "{{ dovecot.serverroot }}/etc/{{ item }}"
    mode:  "0644"
    owner: "root"
  with_items:
    - "openssl.conf"
    - "disabled-users"
    - "virtuser-passwd"

- name: make-config | sbin/mkcert command should be deployed
  template:
    src:   "opt/dovecot/sbin/mkcert.j2"
    dest:  "{{ dovecot.serverroot }}/sbin/mkcert"
    mode:  "0755"
    owner: "root"

- name: make-config | Certificate file should be generated
  shell: >
    ./sbin/mkcert
  args:
    chdir:   "{{ dovecot.serverroot }}"
    creates: "etc/tls/{{ dovecot.config.certificate.commonname }}.crt"

